server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  application:
    name: "cards"
  config:
    import: "configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"