server:
  port: 9000

spring:
  application:
    name: cards

  # ---- DataSource / JPA ----
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

  # ---- Config Server ----
  config:
    import: "configserver:http://configserver-ms:8071/"

  # ---- RabbitMQ ----
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver-ms:8070/eureka/
    fetch-registry: true
    register-with-eureka: true


info:
  app:
    name: "cards"
    description: "learn API for cards"
    version: "1.1.0"
